catalog/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from catalog.views import user, index, image, upload_image, register, search, add_comment, delete_image, settings, \
    delete_image_multiple, test

urlpatterns = [
    path("", index, name="index"),
    #path("user-details/<username>/", user_details, name="user_details"),
    path("image/<int:image_id>/", image, name="image"),
    path("image/<int:id>/delete", delete_image, name="delete-image"),
    path("delete-image-multiple/", delete_image_multiple, name="delete-image-multiple"),
    path("user/<int:id>/", user, name="user"),
    path("user/<int:id>/settings/", settings, name="settings"),
    path("upload-image/", upload_image, name="upload-image"),
    path("search/<query>", search, name="search"),
    path("image/<int:image_id>/add-comment/", add_comment, name="add-comment"),

]

learningDjango/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from catalog.views import register
from learningDjango import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name="register"),
    path('catalog/', include('catalog.urls')),
    path('djangolearn/', include('djangolearn.urls', namespace="djangolearn")),
    # Needed to access translation functions (e.g. gettext)
    # from within JavaScript
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

catalog/models.py
import os

from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import pre_delete

# Custom method that returns canoncial url to access object in HTTP
from django.utils.translation import gettext_lazy


def user_get_absolute_url(self):
    return reverse_lazy("user", args=[str(self.id)])

User.get_absolute_url = user_get_absolute_url

def file_size_validator(value):
    if value.size > settings.MAX_UPLOAD_SIZE:
        msg = "File too big, the maximum file size is: %(size)s bytes"
        raise ValidationError(msg, params={"size": settings.MAX_UPLOAD_SIZE})

class UploadedImage(models.Model):
    class Meta:
        ordering = ["title"]
        verbose_name = gettext_lazy("uploaded image")
        verbose_name_plural = gettext_lazy("uploaded images")

    title = models.CharField(max_length=30,
                             help_text="Required. Max 30 character title for "
                                       "your image")
    description = models.CharField(max_length=150,
                                   help_text="Required.Max 150 character description "
                                             "of your image")
    def get_upload_path(instance, filename):
        return os.path.join("uploaded_images", str(instance.author_id), filename)

    image = models.ImageField(upload_to=get_upload_path,
                              validators=[file_size_validator],
                              help_text=f"Max. file size: {settings.MAX_UPLOAD_SIZE}")
    upload_datetime = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse_lazy("image", args=[str(self.id)])

    def __str__(self):
        return self.title


# Receiver which gets triggered when object is being deleted
@receiver(pre_delete, sender=UploadedImage)
def delete_image_file(sender, instance, using, **kwargs):
    try:
        imgpath = instance.image.path
        os.remove(imgpath)
        # Remove directory if empty
        if len(os.listdir(os.path.dirname(imgpath))) == 0:
            os.rmdir(os.path.dirname(imgpath))
    except:
        pass


class Comment(models.Model):
    uploaded_image = models.ForeignKey(UploadedImage,
                                       on_delete=models.CASCADE)
    text = models.TextField(max_length=1000,
                            help_text="Write your comment. 1000 characters max")
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)

    def get_absolute_url(self):
        pass
        return reverse_lazy("uploaded-images", args=[str(self.uploaded_image.id)])

    def __str__(self):
        return self.text

catalog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from catalog.models import UploadedImage

class UploadedImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ["title", "description", "image"]
        widgets = {
            "image": forms.ClearableFileInput(attrs={"multiple": False}),
            "description": forms.Textarea(attrs={"rows": "4", "cols":"41",
                                                 "placeholder": "My beautiful image"})
        }


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email")
    password1 = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=150, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        # Check whether both passwords don't match
        if cleaned_data["password1"] != cleaned_data["password2"]:
            raise ValidationError("Both passwords must match", code="invalid")
        # Check whether username is already in use
        try:
            username = cleaned_data["username"]
            User.objects.get(username__iexact=username)
            msg = "User named %(user)s already exists"
            raise ValidationError(msg, params={"user": username},
                                  code="invalid")
        except User.DoesNotExist:
            pass
        # Check whether email is already in use
        try:
            email = cleaned_data["email"]
            User.objects.get(email__iexact=email)
            msg = f"Email {email} already in use"
            self.add_error("email", msg)
        except User.DoesNotExist:
            pass

catalog/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User, AnonymousUser
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404
from django.apps import apps
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods, require_POST

from catalog.forms import UploadedImageForm, RegisterForm
from catalog.models import UploadedImage, Comment


def index(request):
    recently_uploaded_images = \
        UploadedImage.objects.order_by("-upload_datetime")
    objects_per_page = 1
    paginator = Paginator(recently_uploaded_images, objects_per_page)
    page_number = request.GET.get("page")
    try:
        page_number = int(page_number)
    except:
        page_number = None
    if page_number and page_number > 1:
        page_obj = paginator.get_page(page_number)
    else:
        page_obj = paginator.get_page(1)
    return render(request, "catalog/index.html", {
        "images": recently_uploaded_images,
        "page_obj": page_obj
    })

def user(request, id):
    user = get_object_or_404(User, id=id)
    uploaded_images = user.uploadedimage_set.all()

    return render(request, "catalog/user.html",
                  {"images": uploaded_images})

def settings(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, "catalog/settings.html", {"user": user})

@require_http_methods(["DELETE"])
def delete_image(request, id):
    try:
        image = UploadedImage.objects.get(id=id)
    except UploadedImage.DoesNotExist:
        json_ = {"error": f"Image with id {id} does not exist"}
    except UploadedImage.MultipleObjectsReturned:
        json_ = {"error": "Internal server error"}
    else:
        image.delete()
    finally:
        return JsonResponse(json_)

@csrf_exempt
@require_http_methods(["DELETE"])
def delete_image_multiple(request):
    deleted_image_ids = request.body.decode("utf-8")
    deleted_image_ids = deleted_image_ids.split(';')
    if not deleted_image_ids:
        return JsonResponse({"error": "No images to delete"})
    for id_ in deleted_image_ids:
        try:
            id_ = int(id_)
        except ValueError:
            return JsonResponse({"error": f"Id {id_} is not a number"})
        try:
            UploadedImage.objects.get(id=id_).delete()
        except UploadedImage.DoesNotExist:
            return JsonResponse({"error": f"Image with id {id_} does not exist"})
        except UploadedImage.MultipleObjectsReturned:
            return JsonResponse({"error": "Internal server error"})
    return JsonResponse({"info": "Deletion sucessfull"})

def image(request, image_id):
    image = get_object_or_404(UploadedImage, pk=image_id)
    return render(request, "catalog/image.html", {"image": image})

def upload_image(request):
    if request.method == "POST":
        form = UploadedImageForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_image = form.save(commit=False)
            user = request.user
            if isinstance(user, AnonymousUser):
                user = User.objects.get(username="AnonymousUser")
            uploaded_image.author = user
            uploaded_image.save()
            messages.info(request, "Image uploaded successfully",
                          extra_tags="message-info")
            return HttpResponseRedirect(reverse("image",
                                                args=[str(uploaded_image.id)]))
        else:
            return render(request, "catalog/upload_image.html", {"form": form})
    else:
        form = UploadedImageForm()
        return render(request, "catalog/upload_image.html", {"form": form})

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
            messages.info(request, "You have been successfully registered!",
                          extra_tags="message-success")
            return HttpResponseRedirect(reverse("login"))
        else:
            return render(request, "catalog/register_form.html", {"form": form})
    else:
        form = RegisterForm()
        return render(request, "catalog/register_form.html", {"form": form})


def search(request, query):
    images_title = UploadedImage.objects.filter(title__icontains=query)
    images_desc = UploadedImage.objects.filter(description__icontains=query)
    users = User.objects.filter(username__icontains=query)
    return render(request, "catalog/search.html", {
        "images_title": images_title,
        "images_desc": images_desc,
        "users": users
    })

@require_POST
def add_comment(request, image_id):
    associated_image = get_object_or_404(UploadedImage, pk=image_id)
    user = request.user
    if isinstance(user, AnonymousUser):
        user = User.objects.get(username="AnonymousUser")
    written_comment_json = json.loads(request.body.decode("utf-8"))
    written_comment = Comment(text=written_comment_json["comment"])
    written_comment.author = user
    written_comment.uploaded_image = associated_image
    written_comment.save()
    return JsonResponse({"username": user.username, "absolute_url": user.get_absolute_url()})

@csrf_exempt
def test(request):
    response = HttpResponse("text")
    print("test")
    return response

catalog/templates/catalog/image.html
{% extends "base.html" %}

{% comment %} In title, display only 43 first characters of image title, for seo optimization {% endcomment %}
{% block title %}Imgify|{{ image.title|slice:":43" }}{% endblock %}
{% block content %}
    <header>
        <h1 class="main-header">{{ image.title }}</h1>
    </header>
    <div class="image-container-full">
        <img src="{{ image.image.url }}" alt="User-uploaded image">
        <p>{{ image.description }}</p>
        <p>
            Uploaded by: <a href="{% url 'user' id=image.author_id %}">{{ image.author.get_username }}</a>
        </p>
        <p>Upload time: {{ image.upload_datetime }}</p>
        <p>
            Image url: <span><a href="{{ request.build_absolute_uri }}">{{ request.build_absolute_uri }}</a></span>
        </p>
        <h3>Comments:</h3>
        <div class="comments-container">
            {% for comment in image.comment_set.all %}
                <p>
                    <a href="{{ comment.author.get_absolute_url }}">{{ comment.author.username }}</a> wrote: {{ comment }}
                </p>
            {% endfor %}
        </div>
        <div class="comment-input-container">
            <textarea id="comment-input" placeholder="Share your mind..."></textarea>
            <button type="button" id="writeButton">Write</button>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends "base.html" %}

{% block title %}Imgify|Main page{% endblock %}
{% block content %}
    <h1 class="main-header">Recently uploaded images</h1>
    {% for image in images %}
        <div class="image-container-thumb">
            <figure>
                <figcaption class="image-title-thumb">{{ image }}</figcaption>
                <a href="{{ image.get_absolute_url }}" title="Click to view image page">
                    <img width="500" height="500" class="image-thumb" src="{{ image.image.url }}" alt="User-uploaded image">
                </a>
            </figure>
            <p class="image-description-thumb">{{ image.description|truncatechars:60 }}</p>
            <p class="image-author-thumb">
                Uploaded by: <a href="{% url 'user' id=image.author_id %}">{{ image.author.username }}</a>
            </p>
            {% load tz %}
            <p class="image-upload-time-thumb">Upload time (UTC): {{ image.upload_datetime |utc }}</p>
        </div>
    {% endfor %}
{% endblock %}
{% block pagination %}
    {{ block.super }}
{% endblock %}

catalog/templates/catalog/register_form.html
{%  extends "base.html" %}

{% block title %}Imgify|Register{% endblock %}
{% block content %}
    <h1 class="main-header">Register</h1>
    <form method="post" id="register-form">
        {% csrf_token %}
        <ul class="non-field-errors">
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        <div>
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }} <span class="help-text">{{ form.username.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.username.errors %}
                    {{ error }}
                {% endfor %}
            </ul>
        </div>
        <div>
            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }} <span class="help-text">{{ form.email.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.email.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }} <span class="help-text">{{ form.password1.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.password1.errors %}
                    {{ error }}
                {% endfor %}
            </ul>
        </div>
        <div>
            <label for="{{ form.password2.id_for_label }}">Repeat password:</label>
            {{ form.password2 }} <span class="help-text">{{ form.password2.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.password2.errors %}
                    {{ error }}
                {% endfor %}
            </ul>
        </div>
        {% comment %}{{ form.as_p }}{% endcomment %}
        <div>
            <input type="submit" value="Register">
        </div>
    </form>
{%  endblock %}

catalog/templates/catalog/search.html
{% extends "base.html" %}
{% block title %}Imgify|search results{% endblock %}
{% block content %}
    <h1 class="main-header">Search results</h1>
    <article>
        <h2 class="results-header">Found by title</h2>
        <div class="results-container">
            {% for image in images_title %}
                <p class="title-paragraph">
                    <a href="{% url 'image' image_id=image.id %}">{{ image.title }}</a>
                </p>
            {% endfor %}
        </div>
        <h2 class="results-header">Found by description</h2>
        <div class="results-container">
            {% for image in images_desc %}
                {% if image.title|lower != image.description|lower %}
                <p class="title-paragraph">
                    <a href="{% url 'image' image_id=image.id %}">{{ image.title }}</a>
                </p>
                {% endif %}
            {% endfor %}
        </div>
        <h2 class="results-header">Users found</h2>
        <div class="results-container">
            {% for user in users %}
                <p class="title-paragraph">
                    <a href="{% url 'user' id=user.id %}">{{ user.username }}</a>
                </p>
            {% endfor %}
        </div>
    </article>
{% endblock %}

catalog/templates/catalog/settings.html
{% extends "base.html" %}
{% block title %}{{ user.username }}|settings{% endblock %}
{% block content %}
    <header>
        <h1 class="main-header">{{ user.username }} - settings</h1>
    </header>
    <div class="main-container">
        <div class="images-pane">
            <h2>Images management</h2>
            <select id="options" name="options">
                <option>--Select an option--</option>
                <option value="delete">Delete</option>
            </select>
            <button type="button" id="go-button">Go</button>
            {% for image in user.uploadedimage_set.all %}
                <div>
                    <img src="{{ image.image.url }}" alt="User-uploaded image">
                    <input type="checkbox" name="selected-image" value="{{ image.id }}">
                </div>
            {% endfor %}
        </div>
        <div class="settings-pane">
            <h2>Settings</h2>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/upload_image.html
{% extends "base.html" %}

{% block title %}Imgify|Upload image{% endblock %}
{% block content %}
    <h1 class="main-header">Upload image</h1>
    <form method="post" enctype="multipart/form-data" id="upload-form">
        {% csrf_token %}
        <ul class="non-field-errors">
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        <div>
            <label for="{{ form.title.id_for_label }}">Title:</label>
            {{ form.title }} <span class="help-text">{{ form.title.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.title.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }} <span class="help-text">{{ form.description.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.title.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <label for="{{ form.image.id_for_label }}">Image:</label>
            {{ form.image }} <span class="help-text">{{ form.image.help_text }}</span>
            <ul class="field-errors">
                {% for error in form.title.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <input type="submit" value="Save">
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/user.html
{% extends "base.html" %}
{% block title %}User: {{ user.username }}{% endblock %}
{% block content %}
    <header>
        <h1 class="main-header">{{ user.username }}</h1>
    </header>
    <div class="images-preview">
        {% for image in images %}
        <p class="image-title-thumb">{{ image.title }}</p>
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ image.image.url }}" alt="User uploaded image">
        </a>
        {% endfor %}
    </div>
{% endblock %}